Vagrant.configure("2") do |config|
  config.vm.box = "StefanScherer/windows_11"
  config.vm.box_version = "2021.12.09"
  config.vm.define "vm_1732468846842093300" do |vm|
    vm.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = 2
      vb.gui = true
      vb.name = "CyberDitto_vm_1732468846842093300"
      vb.customize ["modifyvm", :id, "--vram", "128"]
      vb.customize ["modifyvm", :id, "--accelerate3d", "on"]
    end
  end


  config.vm.provision "file", source: "security_posture.json", destination: "C:/security_posture.json"
 
  config.vm.provision "shell", inline: <<-SHELL
    Write-Host "Setting up Windows 11 environment..."
  SHELL
end